- team_contract.md
- team_norms.md
* [ x] added Team Contract and Team Norms markup documents
Created markup document for both Team Contract and Team Norms. 
---
> Team Documents - Contract and Norms

- client/components/navbar.js
Do not delete branch until travis builds. 
---
> Debug Travis

- .travis.yml
> updated before script database name in yaml file

- server/db/models/plant.js
* changed sequelize letter
---
> changed sequelize letter

- .travis.yml
- client/components/PlantList.js
- client/components/index.js
- client/routes.js
- client/store/index.js
- client/store/plants.js
- server/db/models/plant.js
Cannot yet retrieve plants from server because my branch does not have the api routes feature. I get a 404.
---
I need to merge to master to render PlantList view.
> Product list react redux

- client/components/PlantList.js
- client/store/plants.js
- script/seed.js
images and plant details are now rendering on the /plants view
---
> fixed component bug and image sources in seed file

- client/components/PlantList.js
- client/store/plants.js
- script/seed.js
- server/db/models/plant.js
> Feature: Code review changes

- server/db/models/index.js
- server/db/models/order.js
- server/index.js
created order model and associated the user model with the order model. Now the order model has the foreign key of user_id.
> Order Model and Order/User Association

- server/api/plants.spec.js
updated plant route test file to pass test specs
---
> Updatedvariable in test spec

- server/db/models/address.js
> Created address model

- server/db/models/cartItem.js
- server/db/models/index.js
Added associations on the database association page and then also updated the definition name of CartItem,.
> Associations

- script/seed.js
- server/api/users.js
- server/api/users.spec.js
- server/db/models/user.js
- server/db/models/user.spec.js
Completed backend work on User model, including tests specs.
---
> Feature: User-slice model update, specs, routes

- client/components/auth-form.js
- client/components/user-home.js
- client/store/user.js
- server/auth/google.js
- server/auth/index.js
- server/db/models/user.js
> Confirms nonEmpty fields and adds First Name, Last Name, email Validation

- server/auth/index.js
req.session.userId = the users id
---
> Session UserId

- client/components/navbar.js
updated NavBar to show Cart, Plants Links
> Update Nav Bar

- server/api/cart.js
- server/api/guestCart.js
- server/api/index.js
> finished guestCart get all plants in cart route

- client/components/AddressList.js
- client/components/SingleAddress.js
- client/store/user.js
- server/api/address.js
- server/api/index.js
Address Slice: can add and remove address. API routes created in "/address" file. Updated user reducer to show add and removal of an address from the user. 
---
> Addresses can be added and deleted

- server/api/plants.js
- server/auth/index.js
> Add on cartid to session

- client/components/Cart.js
- client/components/SinglePlant.js
- client/components/UserCart.js
- client/routes.js
- client/store/userCart.js
- server/api/guestCart.js
Maybe now closer to adding an item to the cart!
---
> made some changes to get cart closer to functioning

- server/auth/index.js
> refactored auth bug fix

- client/components/index.js
updated import file name from Auth to auth
---
> updated lower case file on client index

- client/components/SinglePlant.js
- client/store/userCart.js
- server/api/guestCart.js
Logged in user can add items to cart in the correct qty, with the cart view reflecting correct qty and total. Woo!
---
> cart now working

- server/auth/google.js
> Redirect to account page

- client/components/CartTwo.js
- client/components/GuestCart.js
- client/components/SinglePlant.js
- client/components/navbar.js
- client/routes.js
User can successfully be a guest and add items to a cart, and persist over refresh.
---
> functioning guest cart

- client/components/PlantList.js
- client/components/PlantList.spec.js
- client/components/user-home.js
- client/components/user-home.spec.js
> Plant list tests

- client/components/GuestCart.js
- script/seed.js
> minor bug fixes

- client/components/SinglePlant.js
> bugs fixed

- client/components/SinglePlant.js
adds the plants ordertotal on the single plant page for local storage
---
> total add fixed

- client/components/PlantList.spec.js
- client/components/SinglePlant.js
- client/components/SinglePlant.spec.js
> Frontend tests

- client/components/Checkout.js
- client/components/GuestCart.js
- client/components/UserCart.js
functional buttons now render the checkout page with correct total at top.
---
> functional checkout button

- .vscode/settings.json
- client/components/Cart.js
- client/components/CartTwo.js
- client/components/GuestCart.js
- client/components/SinglePlant.js
- client/components/UserCart.js
- client/components/auth-form.js
- public/style.css
> Styling cart

- client/components/Cart.js
- client/components/Orders.js
- client/components/user-home.js
- public/style.css
> User home styling
